### ISSUE TITLE
SimpleMessageSpout can't work. 

### ISSUE THREAD

**Issue by handmail** [rocketmq/rocketmq-storm#1]
2015-04-15T19:47:30.094+0800 b.s.util [ERROR] Async loop died!
java.util.NoSuchElementException: null
        at java.util.LinkedList.remove(LinkedList.java:788) ~[na:1.6.0_45]
        at java.util.LinkedList.removeFirst(LinkedList.java:134) ~[na:1.6.0_45]
        at backtype.storm.daemon.executor$fn__3373$fn__3388$fn__3417$fn__3419.invoke(executor.clj:549) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.daemon.executor$fn__3373$fn__3388$fn__3417.invoke(executor.clj:545) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) ~[storm-core-0.9.3.jar:0.9.3]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
2015-04-15T19:47:30.094+0800 b.s.d.executor [ERROR] 
java.util.NoSuchElementException: null
        at java.util.LinkedList.remove(LinkedList.java:788) ~[na:1.6.0_45]
        at java.util.LinkedList.removeFirst(LinkedList.java:134) ~[na:1.6.0_45]
        at backtype.storm.daemon.executor$fn__3373$fn__3388$fn__3417$fn__3419.invoke(executor.clj:549) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.daemon.executor$fn__3373$fn__3388$fn__3417.invoke(executor.clj:545) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) ~[storm-core-0.9.3.jar:0.9.3]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
2015-04-15T19:47:30.132+0800 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: java.lang.NullPointerException
        at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:128) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:99) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.disruptor$consume_loop_STAR_$fn__1460.invoke(disruptor.clj:94) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) ~[storm-core-0.9.3.jar:0.9.3]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
Caused by: java.lang.NullPointerException: null
        at clojure.lang.RT.intCast(RT.java:1087) ~[clojure-1.5.1.jar:na]
        at backtype.storm.daemon.worker$mk_transfer_fn$fn__3549.invoke(worker.clj:129) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.daemon.executor$start_batch_transfer__GT_worker_handler_BANG_$fn__3283.invoke(executor.clj:258) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.disruptor$clojure_handler$reify__1447.onEvent(disruptor.clj:58) ~[storm-core-0.9.3.jar:0.9.3]
        at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:125) ~[storm-core-0.9.3.jar:0.9.3]
        ... 6 common frames omitted

**Comment by vongosling** [comment]
how do you run it？cluster mode or local mode

**Comment by vongosling** [comment]
Try to debug at some clojure RT class iniCast method,may be you will find something miss.

RT.intCast(stormConf
				.get(Config.TOPOLOGY_BUILTIN_METRICS_BUCKET_SIZE_SECS));

**Comment by theGreatHeisenberg** [comment]
@handmail  : Did you find the reason?
